apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: gardener-extensions-validator-vsphere
webhooks:
- name: validation.vsphere.provider.extensions.gardener.cloud
  rules:
  - apiGroups:
    - "core.gardener.cloud"
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - shoots
  failurePolicy: Fail
  objectSelector: {}
  namespaceSelector: {}
  sideEffects: None
  admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    url: "https://localhost:9443/webhooks/validate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrekNDQWVPZ0F3SUJBZ0lSQU1nK1Z0cG5EVm55TEpuNjZFNjFXekF3RFFZSktvWklodmNOQVFFTEJRQXcKRnpFVk1CTUdBMVVFQXhNTVoyRnlaR1Z1WlhJdFpHVjJNQjRYRFRJeE1ERXlNVEV3TXpNeE5Wb1hEVE14TURFeQpNVEV3TXpNeE5Wb3dGekVWTUJNR0ExVUVBeE1NWjJGeVpHVnVaWEl0WkdWMk1JSUJJakFOQmdrcWhraUc5dzBCCkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXREV2R2MEhqRmt5b2xvenlYbXYzSUltQ1h0d3FpaVpEYVJ6M0ZGLzEKdTNQdENvaXJSMGYyejNmdWcwenpPMFovbERyT21jcS9Lc3kzM1JSR3hWK2p0MFQzaEo4Nk91bUN3U0JOZ0ZCYworWWJZMXkrZXIvWWc1c0wvMlkyeDIyUkV5bVYxR3I2SnlSd2FOc0hua3hOYmhPYTNBdnNOR2J3WnRHTHJxL05nCnhFVjM3ZEZicTZrZ3BQeVRiZC92YktYU3BFVEI3Ni9hWXoxd1FMeklZSXNscUFucmNMMnd4cmZvYlBwSG1RcDYKUzJxKy9DaFJpNCszTjlKTkRyMWxncktMKzFHYTM2VGxObjAvVUVoUXpwajFWb29DTEFJQnVaYlEwalVQSHJtUgprZlY4U2RUN1JuS2toTDY4THNhcFBTT1JqZUZaT2VkcnJjbElvaDQ1UWR2Yk5RSURBUUFCbzBJd1FEQU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVV4VDFZQ1R2Q016WHoKd3c5QWpiV2Z3Q3crZzFrd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFSmR4dnA3dVpMenA2TUJXUW1RKzhsRgpZQkpHMy9IUG10YzlGM1NxZk4rdEFQVnRlb2NOWWkzck94L2diTDU5M285VFJrVVdKc0tWcWhnUXorbXdrYTRQCnhVbytRRjNwaU80ejBVTzhvUTdwZmd4bkhJR1RzSmFMZzAzVTBGdDJ5dUtTSlRoa0FIelNPK205dEw2UVdTdXIKSmxnWEVnbmRCd1F4NGJwRDFnRUZseFEwUCttMmJTRXhQUDJtYU0rNFdNT3BDdGIxc1l6a2FtTURkVXFJcWp6dQpiZVErTEFsQnp0V2dQNU5iSWt4UmVrOVlHUGtLb0lHVy9kQ2FlcFJFUDl4ZXJra25nbDJuUjJHZy83aWhORnVECk8zTnovZTdKaWlvWnlsVzdLcWNTL2lveGdzM1duTFJySit5QkZjNG1iTUpIMU1Ya25ueDVRa2lVY0lIUWN5ND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
- name: secrets.validation.vsphere.provider.extensions.gardener.cloud
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - UPDATE
    resources:
    - secrets
  failurePolicy: Fail
  objectSelector: {}
  namespaceSelector: {}
  sideEffects: None
  admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      namespace: garden
      name: gardener-extension-admission-vsphere
      path: /webhooks/validate/secrets
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrekNDQWVPZ0F3SUJBZ0lSQU1nK1Z0cG5EVm55TEpuNjZFNjFXekF3RFFZSktvWklodmNOQVFFTEJRQXcKRnpFVk1CTUdBMVVFQXhNTVoyRnlaR1Z1WlhJdFpHVjJNQjRYRFRJeE1ERXlNVEV3TXpNeE5Wb1hEVE14TURFeQpNVEV3TXpNeE5Wb3dGekVWTUJNR0ExVUVBeE1NWjJGeVpHVnVaWEl0WkdWMk1JSUJJakFOQmdrcWhraUc5dzBCCkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXREV2R2MEhqRmt5b2xvenlYbXYzSUltQ1h0d3FpaVpEYVJ6M0ZGLzEKdTNQdENvaXJSMGYyejNmdWcwenpPMFovbERyT21jcS9Lc3kzM1JSR3hWK2p0MFQzaEo4Nk91bUN3U0JOZ0ZCYworWWJZMXkrZXIvWWc1c0wvMlkyeDIyUkV5bVYxR3I2SnlSd2FOc0hua3hOYmhPYTNBdnNOR2J3WnRHTHJxL05nCnhFVjM3ZEZicTZrZ3BQeVRiZC92YktYU3BFVEI3Ni9hWXoxd1FMeklZSXNscUFucmNMMnd4cmZvYlBwSG1RcDYKUzJxKy9DaFJpNCszTjlKTkRyMWxncktMKzFHYTM2VGxObjAvVUVoUXpwajFWb29DTEFJQnVaYlEwalVQSHJtUgprZlY4U2RUN1JuS2toTDY4THNhcFBTT1JqZUZaT2VkcnJjbElvaDQ1UWR2Yk5RSURBUUFCbzBJd1FEQU9CZ05WCkhROEJBZjhFQkFNQ0FhWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVV4VDFZQ1R2Q016WHoKd3c5QWpiV2Z3Q3crZzFrd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFSmR4dnA3dVpMenA2TUJXUW1RKzhsRgpZQkpHMy9IUG10YzlGM1NxZk4rdEFQVnRlb2NOWWkzck94L2diTDU5M285VFJrVVdKc0tWcWhnUXorbXdrYTRQCnhVbytRRjNwaU80ejBVTzhvUTdwZmd4bkhJR1RzSmFMZzAzVTBGdDJ5dUtTSlRoa0FIelNPK205dEw2UVdTdXIKSmxnWEVnbmRCd1F4NGJwRDFnRUZseFEwUCttMmJTRXhQUDJtYU0rNFdNT3BDdGIxc1l6a2FtTURkVXFJcWp6dQpiZVErTEFsQnp0V2dQNU5iSWt4UmVrOVlHUGtLb0lHVy9kQ2FlcFJFUDl4ZXJra25nbDJuUjJHZy83aWhORnVECk8zTnovZTdKaWlvWnlsVzdLcWNTL2lveGdzM1duTFJySit5QkZjNG1iTUpIMU1Ya25ueDVRa2lVY0lIUWN5ND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
