apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: shoot-operator-vsphere-gcloud-fielglass-1
  namespace: default
data:
  nsxt_edge_cluster: {{ b64enc "edge-cluster" }}
  nsxt_host: {{ b64enc .Values.privateCloud.nsx.internalip }}
  nsxt_password: {{ b64enc .Values.nsxCredentials.password }}
  nsxt_snat_ip_pool: {{ b64enc "snat-ippool" }} # this is created in .ci/terraform/main.tf
  nsxt_t0_gateway: {{ b64enc "Provider-LR" }}
  nsxt_transport_zone:  {{ b64enc "TZ-OVERLAY" }}
  nsxt_username: {{ b64enc .Values.nsxCredentials.username }}
