apiVersion: v1
data:
  "csi-migration": "false"
  "csi-auth-check": "true"
  "online-volume-extend": "true"
kind: ConfigMap
metadata:
  name: internal-feature-states.csi.vsphere.vmware.com
  namespace: {{ .Release.Namespace }}