apiVersion: testmachinery.sapcloud.io/v1beta1
kind: Testrun
metadata:
  generateName: tm-extension-vsphere-
  namespace: default
spec:
  ttlSecondsAfterFinished: 172800 # 2 days
  locationSets:
    {{- if .Values.localLocation }}
    - default: true
      name: local
      locations:
        - type: local
          hostPath: /tmp/tm # hostpath to a directory containing TestDefinition
    {{ else }}
    - default: true
      name: provider-vsphere
      locations:
        - type: git
          repo: https://github.com/gardener/gardener-extension-provider-vsphere.git
      {{- if .Values.revision }}
          revision: {{ .Values.revision }}
      {{- end }}
    {{ end }}

  {{/* Config items are global to for both gcve-setup and gcve-teardown */}}
  config:
    - name: SERVICEACCOUNT_JSON
      type: env
      valueFrom:
        secretKeyRef:
          name: shoot-operator-vsphere
          key: serviceaccount.json
    - name: REGION
      type: env
      value: us-east4

  testflow:
    - name: gcve-setup
      definition:
        name: gcve-setup
        config:
          - name: PHASE
            type: env
            value: dummy # should be setup for proper production use
    - name: infrastructure-test
      dependsOn: [gcve-setup]
      definition:
        name: infrastructure-test

  onExit:
    - name: gcve-teardown
      condition: always
      definition:
        name: gcve-setup
        config:
          - name: PHASE
            type: env
            value: shutdown
